title: MineColonies Wiki
description: >-
  MineColonies Wiki
remote-theme: jekyll/minima

baseurl: /
source: ./src
destination: ./build
#incremental: true

markdown: kramdown
plugins:
- jekyll-seo-tag
